In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [4]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
#Preprocessing the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [6]:
#Encoding the categorical data
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])

In [7]:
#One hot encoding for the 'Geography' column
ohe = OneHotEncoder()
geography_encoded = ohe.fit_transform(data[['Geography']]).toarray()    
geography_df = pd.DataFrame(geography_encoded, columns=ohe.get_feature_names_out(['Geography']))

In [8]:
geography_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [9]:
#Combining the one-hot encoded 'Geography' columns with the original dataset
data = pd.concat([data.drop('Geography',axis=1), geography_df], axis=1)

In [10]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
#Splitting the dataset into features and target variable
X = data.drop('EstimatedSalary', axis=1)
Y = data['EstimatedSalary']

In [12]:
#Splitting the dataset into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2, random_state=42)

In [13]:
#Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
#Save the encoders and scaler for later use
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(ohe, file)  

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN REGRESION PROBLEM STATEMENT

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [20]:
#Build the model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')
])

#compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/Users/asmitakabra/Library/Python/3.9/lib/python/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [22]:
#Set up tensorboard callback
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [23]:
#Set up early stopping and TensorBoard callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [24]:
#Train the model
history = model.fit(X_train, Y_train, validation_data = (X_test, Y_test), epochs=100,  callbacks=[early_stopping,tensorboard_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100145.8047 - mae: 100145.8047 - val_loss: 98573.0625 - val_mae: 98573.0625
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100437.8750 - mae: 100437.8750 - val_loss: 97385.6953 - val_mae: 97385.6953
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98375.3281 - mae: 98375.3281 - val_loss: 94280.4766 - val_mae: 94280.4766
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 94779.3906 - mae: 94779.3906 - val_loss: 88937.7812 - val_mae: 88937.7812
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 88697.4375 - mae: 88697.4375 - val_loss: 81729.8828 - val_mae: 81729.8828
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 82167.2031 - mae: 82167.2031 - val_loss: 73627.3672 - val_mae: 73627.3672
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 73761.4141 - mae: 73761.4141 - val_loss: 65907.6016 - val_mae: 65907.6016
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 65372.2930 - mae: 65372.2930 - val_loss: 59534.9922 - val_mae: 59534.9922
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 59398.5977 - mae: 59398.5977 - val_loss: 55107.4727 - val_mae: 55107.4727
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54243.9766 - mae: 54243.9766 - val_loss: 52578.0234 - val_mae: 52578.0234
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52482.6133 - mae: 52482.6133 - val_loss: 51443.1016 - val_mae: 51443.1016
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51142.9531 - mae: 51142.9531 - val_loss: 51041.6406 - val_mae: 51041.6406
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50513.7344 - mae: 50513.7344 - val_loss: 50887.0078 - val_mae: 50887.0078
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50071.5195 - mae: 50071.5195 - val_loss: 50800.8086 - val_mae: 50800.8086
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50542.8633 - mae: 50542.8633 - val_loss: 50758.8242 - val_mae: 50758.8242
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50360.3359 - mae: 50360.3359 - val_loss: 50720.4883 - val_mae: 50720.4883
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49677.1289 - mae: 49677.1289 - val_loss: 50689.9336 - val_mae: 50689.9336
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49596.5977 - mae: 49596.5977 - val_loss: 50667.2695 - val_mae: 50667.2695
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49794.7852 - mae: 49794.7852 - val_loss: 50638.1445 - val_mae: 50638.1445
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49637.1719 - mae: 49637.1719 - val_loss: 50612.7031 - val_mae: 50612.7031
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49770.7930 - mae: 49770.7930 - val_loss: 50593.4375 - val_mae: 50593.4375
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50314.3164 - mae: 50314.3164 - val_loss: 50566.3633 - val_mae: 50566.3633
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50221.9219 - mae: 50221.9219 - val_loss: 50553.5586 - val_mae: 50553.5586
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49905.6172 - mae: 49905.6172 - val_loss: 50538.7734 - val_mae: 50538.7734
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50278.0508 - mae: 50278.0508 - val_loss: 50520.6992 - val_mae: 50520.6992
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49056.3242 - mae: 49056.3242 - val_loss: 50518.2070 - val_mae: 50518.2070
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49579.3555 - mae: 49579.3555 - val_loss: 50503.0859 - val_mae: 50503.0859
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50453.4883 - mae: 50453.4883 - val_loss: 50488.3984 - val_mae: 50488.3984
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49849.4727 - mae: 49849.4727 - val_loss: 50482.4688 - val_mae: 50482.4688
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49872.9805 - mae: 49872.9805 - val_loss: 50482.0078 - val_mae: 50482.0078
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50109.0938 - mae: 50109.0938 - val_loss: 50465.3320 - val_mae: 50465.3320
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49411.9023 - mae: 49411.9023 - val_loss: 50470.6406 - val_mae: 50470.6406
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49676.5312 - mae: 49676.5312 - val_loss: 50457.1133 - val_mae: 50457.1133
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49904.5820 - mae: 49904.5820 - val_loss: 50451.4375 - val_mae: 50451.4375
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49846.4922 - mae: 49846.4922 - val_loss: 50443.8750 - val_mae: 50443.8750
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49848.4609 - mae: 49848.4609 - val_loss: 50438.8203 - val_mae: 50438.8203
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49638.1094 - mae: 49638.1094 - val_loss: 50431.8789 - val_mae: 50431.8789
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49415.5742 - mae: 49415.5742 - val_loss: 50432.9961 - val_mae: 50432.9961
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49564.0703 - mae: 49564.0703 - val_loss: 50423.7305 - val_mae: 50423.7305
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49862.9609 - mae: 49862.9609 - val_loss: 50417.6445 - val_mae: 50417.6445
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49914.6445 - mae: 49914.6445 - val_loss: 50411.0586 - val_mae: 50411.0586
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50078.5977 - mae: 50078.5977 - val_loss: 50418.1523 - val_mae: 50418.1523
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49466.0586 - mae: 49466.0586 - val_loss: 50411.2031 - val_mae: 50411.2031
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49742.8789 - mae: 49742.8789 - val_loss: 50406.1406 - val_mae: 50406.1406
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49677.9219 - mae: 49677.9219 - val_loss: 50409.6094 - val_mae: 50409.6094
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49094.4180 - mae: 49094.4180 - val_loss: 50410.2188 - val_mae: 50410.2188
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49284.0742 - mae: 49284.0742 - val_loss: 50394.0781 - val_mae: 50394.0781
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49749.6367 - mae: 49749.6367 - val_loss: 50399.9297 - val_mae: 50399.9297
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49035.1719 - mae: 49035.1719 - val_loss: 50403.5938 - val_mae: 50403.5938
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49643.4102 - mae: 49643.4102 - val_loss: 50402.5586 - val_mae: 50402.5586
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49489.3789 - mae: 49489.3789 - val_loss: 50395.6250 - val_mae: 50395.6250
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49432.8828 - mae: 49432.8828 - val_loss: 50384.3164 - val_mae: 50384.3164
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49725.1289 - mae: 49725.1289 - val_loss: 50402.1836 - val_mae: 50402.1836
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50206.8281 - mae: 50206.8281 - val_loss: 50376.9023 - val_mae: 50376.9023
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49301.8320 - mae: 49301.8320 - val_loss: 50377.3125 - val_mae: 50377.3125
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49430.6914 - mae: 49430.6914 - val_loss: 50381.5703 - val_mae: 50381.5703
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 48913.7109 - mae: 48913.7109 - val_loss: 50379.2695 - val_mae: 50379.2695
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49465.4336 - mae: 49465.4336 - val_loss: 50372.6094 - val_mae: 50372.6094
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49815.8789 - mae: 49815.8789 - val_loss: 50381.3672 - val_mae: 50381.3672
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50020.5547 - mae: 50020.5547 - val_loss: 50381.9219 - val_mae: 50381.9219
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49541.8516 - mae: 49541.8516 - val_loss: 50380.3828 - val_mae: 50380.3828
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49681.1250 - mae: 49681.1250 - val_loss: 50379.5039 - val_mae: 50379.5039
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49599.3203 - mae: 49599.3203 - val_loss: 50378.3320 - val_mae: 50378.3320
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49055.5938 - mae: 49055.5938 - val_loss: 50388.5156 - val_mae: 50388.5156
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49192.5469 - mae: 49192.5469 - val_loss: 50371.7695 - val_mae: 50371.7695
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49448.0938 - mae: 49448.0938 - val_loss: 50391.6367 - val_mae: 50391.6367
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49281.9805 - mae: 49281.9805 - val_loss: 50387.3633 - val_mae: 50387.3633
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49745.6367 - mae: 49745.6367 - val_loss: 50366.8711 - val_mae: 50366.8711
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50204.6953 - mae: 50204.6953 - val_loss: 50377.1445 - val_mae: 50377.1445
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49396.7734 - mae: 49396.7734 - val_loss: 50392.7969 - val_mae: 50392.7969
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49833.1680 - mae: 49833.1680 - val_loss: 50392.9336 - val_mae: 50392.9336
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49649.9844 - mae: 49649.9844 - val_loss: 50378.2578 - val_mae: 50378.2578
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49261.4297 - mae: 49261.4297 - val_loss: 50389.4375 - val_mae: 50389.4375
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49590.2344 - mae: 49590.2344 - val_loss: 50396.5352 - val_mae: 50396.5352
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49240.7383 - mae: 49240.7383 - val_loss: 50393.8281 - val_mae: 50393.8281
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49248.7891 - mae: 49248.7891 - val_loss: 50406.7773 - val_mae: 50406.7773
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49173.7969 - mae: 49173.7969 - val_loss: 50395.2188 - val_mae: 50395.2188
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49371.5781 - mae: 49371.5781 - val_loss: 50394.8750 - val_mae: 50394.8750

In [25]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6008 (pid 33451), started 0:00:08 ago. (Use '!kill 33451' to kill it.)

In [28]:
##Evaluate the model
test_loss, test_mae = model.evaluate(X_test, Y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51164.1523 - mae: 51164.1523
Test Loss: 50366.87109375, Test MAE: 50366.87109375

In [29]:
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.